-- ===============================
-- TABELAS
-- ===============================

CREATE TABLE CATEGORIAS_FINANCEIRAS (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(255),
    TIPO ENUM('ENTRADA','SAIDA') NOT NULL,
    ATIVO TINYINT(1) NOT NULL DEFAULT 1,
    DATA_CRIACAO DATE NOT NULL
) 
CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL UNIQUE,
    TELEFONE CHAR(11) NOT NULL CHECK (TELEFONE NOT LIKE '0%'),
    ENDERECO VARCHAR(120) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
) 
CREATE TABLE TIPO_USUARIO (
    ID_TIPO_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_TIPO VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(100)
) 
CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    STATUS TINYINT(1) NOT NULL DEFAULT 1,
    DATA_CRIACAO DATE NOT NULL,
    DATA_ULTIMO_LOGIN DATE,
    FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
) 
CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    CNPJ CHAR(14) NOT NULL UNIQUE,
    TELEFONE CHAR(11) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL
) 
CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    CATEGORIA VARCHAR(40) NOT NULL,
    DESCRICAO VARCHAR(255),
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE_ATUAL INT NOT NULL DEFAULT 0
) 
CREATE TABLE COMPRAS (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    DATA_COMPRA DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
) 
CREATE TABLE ITENS_COMPRA (
    ID_ITEM_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPRA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    CUSTO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
) 
CREATE TABLE ESTOQUE_MOVIMENTACOES (
    ID_MOV INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    TIPO ENUM('ENTRADA','SAIDA') NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_MOV DATE NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
) 
CREATE TABLE PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
) 
CREATE TABLE ITENS_PEDIDOS (
    ID_ITEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
) 
CREATE TABLE ENVIO_TRANSPORTADORA (
    ID_ENVIO_TRANSPORTADORA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL UNIQUE,  -- RELACIONAMENTO 1:1
    TRANSPORTADORA VARCHAR(50) NOT NULL,
    STATUS_DE_RETIRADA VARCHAR(20) NOT NULL,
    DATA_DE_RETIRADA DATE,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
) 
CREATE TABLE TRANSACOES_FINANCEIRAS (
    ID_TRANSACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT NOT NULL,
    DATA_TRANSACAO DATE NOT NULL,
    TIPO ENUM('ENTRADA','SAIDA') NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DESCRICAO VARCHAR(255),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS_FINANCEIRAS(ID_CATEGORIA)
) 
CREATE TABLE NOTA_FISCAL (
    ID_NOTA_FISCAL INT AUTO_INCREMENT PRIMARY KEY,
    ID_TRANSACAO INT NOT NULL UNIQUE,  -- 1:1
    NUMERO_NOTA INT NOT NULL,
    CHAVE_ACESSO CHAR(44) NOT NULL UNIQUE,
    DATA_EMISSAO DATE NOT NULL,
    TIPO_NOTA ENUM('ENTRADA','SAIDA') NOT NULL,
    STATUS ENUM('ATIVA','CANCELADA') NOT NULL,
    FOREIGN KEY (ID_TRANSACAO) REFERENCES TRANSACOES_FINANCEIRAS(ID_TRANSACAO)
) 
CREATE TABLE CHAMADOS_SUPORTE (
    ID_CHAMADO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(255),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
) 
-- ===============================
-- TABELA N:N (PEDIDOS X USUÁRIOS)
-- EXEMPLO DE RELACIONAMENTO N:N
-- ===============================
CREATE TABLE PEDIDOS_USUARIOS (
    ID_PEDIDO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_USUARIO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
) 

SET FOREIGN_KEY_CHECKS = 1;

